excluded:
  - Carthage
  - Pods
  - .build

line_length: 100

disabled_rules:
  - todo

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 500
  error: 1000

reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji, sonarqube, markdown, github-actions-logging)