included: # paths to include during linting. `--path` is ignored if present.
  - Sources
  - Tests
  - Package.swift

excluded:
  - Carthage
  - Pods
  - .build
  - Tests/CoreHwpTests/XCTestManifests.swift

line_length: 100

disabled_rules:
  - todo

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 500
  error: 700

reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji, sonarqube, markdown, github-actions-logging)