included: # paths to include during linting. `--path` is ignored if present.
  - Sources
  - Tests
  - Package.swift

excluded:
  - Carthage
  - Pods
  - .build
  - Tests/CoreHwpTests/XCTestManifests.swift

line_length:
  warning: 100
  error: 120

disabled_rules:
  - todo

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 500
  error: 700

custom_rules:
  no_xctassert:
    name: "No XCTAssert"
    regex: "(XCTAssert)"
    match_kinds:
      - comment
      - identifier
    message: "Use Nimble expect ~ to be ~ pattern"
    severity: error

# reporter type (xcode, json, csv, checkstyle, junit, html, emoji, sonarqube, markdown, github-actions-logging)
reporter: "xcode"
