name: Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DEVELOPER_DIR: /Applications/Xcode_12.app/Contents/Developer

jobs:
  coverage:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: xcodebuild -scheme HwpKit-Package -resolvePackageDependencies -resultBundlePath HwpKit-Package.xcresult test
    - name: Make Report
      run: xcrun xccov view --report --json HwpKit-Package.xcresult > report.json
    - name: Code Climate Coverage Action
      uses: paambaati/codeclimate-action@v2.7.4
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      with:
        coverageLocations: ${{github.workspace}}/report.json:json
