name: Coverage

on:
  push:
    branches:
      - master

jobs:
  coverage:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v --enable-code-coverage
    - name: Prepare Codecov
      run: xcrun llvm-cov export -format="lcov" .build/debug/HwpKitPackageTests.xctest/Contents/MacOS/HwpKitPackageTests -instr-profile .build/debug/codecov/default.profdata > info.lcov
    - name: Upload to Codecov
      run: bash <(curl https://codecov.io/bash)
      env: 
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      
