name: Coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  coverage:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: swift test -v --enable-test-discovery --enable-code-coverage
    - name: Prepare Codecov
      run: xcrun llvm-cov export -format="lcov" .build/debug/Hwp-SwiftPackageTests.xctest/Contents/MacOS/Hwp-SwiftPackageTests -instr-profile .build/debug/codecov/default.profdata > raw.lcov
    - name: Install lcov
      run: brew install lcov
    - name: Extract
      run: lcov -e raw.lcov "*Hwp-Swift/Sources*" -o info.lcov
    - name: Code Climate Coverage Action
      uses: paambaati/codeclimate-action@v2.7.5
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      with:
        coverageLocations: ${{github.workspace}}/info.lcov:lcov
