name: Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  coverage:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - uses: fwal/setup-swift@v1
      with:
        swift-version: "5.3"
    - name: Resolve Dependencies
      run: swift package resolve
    - name: Run tests
      run: xcodebuild -scheme HwpKit-Package -resultBundlePath HwpKit-Package.xcresult test
    - name: Make Report
      run: xcrun xccov view --report --json HwpKit-Package.xcresult > report.json
    - name: Code Climate Coverage Action
      uses: paambaati/codeclimate-action@v2.7.4
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      with:
        coverageLocations: ${{github.workspace}}/*.lcov:lcov
