name: Documentation

on:
  push:
    branches: [main]

jobs:
  documentation:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Generate Documentation
        uses: SwiftDocOrg/swift-doc@master
        with:
          inputs: "Sources"
          module-name: Hwp-Swift
          output: "Documentation"
      - name: Upload Documentation to Wiki
        uses: SwiftDocOrg/github-wiki-publish-action@v1
        with:
          path: "Documentation"
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      - name: Release Drafter
        uses: release-drafter/release-drafter@v5.12.1
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
