name: Lint

on:
  push:
    branches:
      - main
    paths:
      - '**.swift'

  pull_request:
    branches:
      - main
    paths:
      - '**.swift'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: GitHub Action for SwiftLint
      uses: norio-nomura/action-swiftlint@3.1.0
