name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  format:
    name: SwiftFormat
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install SwiftFormat
      run: brew install swiftformat
    - name: Lint SwiftFormat
      run: swiftformat --lint .

  lint:
    name: SwiftLint
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install SwiftLint
      run: brew install swiftlint
    - name: Lint SwiftLint
      run: swiftlint
