name: Test Linux

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test Swift@${{ matrix.swift }} on Linux

    runs-on: ubuntu-20.04
    container: swift:${{ matrix.swift }}-focal
    strategy:
      fail-fast: false
      matrix:
        swift: ["5.2", "5.6"]

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: |
        swift --version
        swift test -v --enable-test-discovery
