name: Test-Ubuntu

on: [ push, pull_request ]

jobs:
  test:
    name: Test on ${{ matrix.os }} and swift ${{ matrix.swift }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest]
        swift: ["4.2", "5.0", "5.1", "5.2", "5.3"]

    steps:
    - uses: actions/checkout@v2
    - name: Setup Swift
      uses: fwal/setup-swift@v1.2.0
      with:
        swift-version: ${{ matrix.swift }}
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
