name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test on Swift 5.3
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - uses: fwal/setup-swift@v1
      with:
        swift-version: "5.3"
    - name: Get Swift version
      run:  swift --version
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
