name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test on ${{ matrix.os }} and swift ${{ matrix.swift }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest]
        swift: ["5.1", "5.2", "5.3"]

    steps:
    - uses: actions/checkout@v2
    - name: Install SwiftEnv
      run: brew install kylef/formulae/swiftenv
    - name: Set Swift ${{ matrix.swift }}
      run: swiftenv global ${{ matrix.swift }}
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
